---

on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  lint-shell-scripts:
    name: Lint Shell Scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint shell scripts
        uses: ludeeus/action-shellcheck@master
